package project_oop.view;

import com.formdev.flatlaf.ui.FlatBorder;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author riskychici
 */
public class karyawan extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(karyawan.class.getName());
    private final String CARI_PLACEHOLDER = "Cari Karyawan";
    private final java.awt.Color PLACEHOLDER_COLOR = new java.awt.Color(153, 153, 153);

    /**
     * Creates new form menu
     */
    public karyawan() {
        initComponents();
        java.awt.EventQueue.invokeLater(() -> {
            setInitialPlaceholder();
        });
        getContentPane().requestFocusInWindow();
    }

    private void setInitialPlaceholder() {
        // Untuk Username
        kolomPencarian.setText(CARI_PLACEHOLDER);
        kolomPencarian.setForeground(PLACEHOLDER_COLOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDaftarKaryawan = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        kolomPencarian = new javax.swing.JTextField();
        btnTambahMenu = new javax.swing.JButton();
        btnSideBeranda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSidePesanan = new javax.swing.JButton();
        btnSideDaftarMenu = new javax.swing.JButton();
        btnSideKaryawan = new javax.swing.JButton();
        btnSideMeja = new javax.swing.JButton();
        btnSidePembayaran = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelDaftarKaryawan.setBackground(new java.awt.Color(252, 250, 248));
        tabelDaftarKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelDaftarKaryawan.setName(""); // NOI18N
        jScrollPane1.setViewportView(tabelDaftarKaryawan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 1350, 720));

        btnCari.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-cari.png"))); // NOI18N
        btnCari.setBorderPainted(false);
        btnCari.setContentAreaFilled(false);
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-cari-hover.png"))); // NOI18N
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 156, 100, 45));

        kolomPencarian.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        kolomPencarian.setToolTipText("");
        kolomPencarian.setBorder(null);
        kolomPencarian.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kolomPencarianFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kolomPencarianFocusLost(evt);
            }
        });
        kolomPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomPencarianActionPerformed(evt);
            }
        });
        getContentPane().add(kolomPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 161, 265, 35));

        btnTambahMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-tambahMenu.png"))); // NOI18N
        btnTambahMenu.setBorderPainted(false);
        btnTambahMenu.setContentAreaFilled(false);
        btnTambahMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-tambahMenu-hover.png"))); // NOI18N
        getContentPane().add(btnTambahMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 59, 160, 51));

        btnSideBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-beranda-nonAktif.png"))); // NOI18N
        btnSideBeranda.setBorderPainted(false);
        btnSideBeranda.setContentAreaFilled(false);
        btnSideBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSideBeranda.setDefaultCapable(false);
        btnSideBeranda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-beranda-hover.png"))); // NOI18N
        getContentPane().add(btnSideBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 128, 266, 63));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 54, 35));
        jLabel1.setText("Daftar Karyawan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 73, 221, 36));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(125, 125, 125));
        jLabel2.setText("Daftar Karyawan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 24, 221, 21));

        btnSidePesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-pesanan-nonAktif.png"))); // NOI18N
        btnSidePesanan.setBorderPainted(false);
        btnSidePesanan.setContentAreaFilled(false);
        btnSidePesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSidePesanan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-pesanan-hover.png"))); // NOI18N
        getContentPane().add(btnSidePesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 204, 266, 63));

        btnSideDaftarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-daftarMenu-nonAktif.png"))); // NOI18N
        btnSideDaftarMenu.setBorderPainted(false);
        btnSideDaftarMenu.setContentAreaFilled(false);
        btnSideDaftarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSideDaftarMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-daftarMenu-hover.png"))); // NOI18N
        getContentPane().add(btnSideDaftarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 279, 266, 63));

        btnSideKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-karyawan-aktif.png"))); // NOI18N
        btnSideKaryawan.setBorderPainted(false);
        btnSideKaryawan.setContentAreaFilled(false);
        btnSideKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnSideKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 354, 266, 63));

        btnSideMeja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-meja-nonAktif.png"))); // NOI18N
        btnSideMeja.setBorderPainted(false);
        btnSideMeja.setContentAreaFilled(false);
        btnSideMeja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSideMeja.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-meja-hover.png"))); // NOI18N
        getContentPane().add(btnSideMeja, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 427, 266, 63));

        btnSidePembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-pembayaran-nonAktif.png"))); // NOI18N
        btnSidePembayaran.setBorderPainted(false);
        btnSidePembayaran.setContentAreaFilled(false);
        btnSidePembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSidePembayaran.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-sidebar-pembayaran-hover.png"))); // NOI18N
        getContentPane().add(btnSidePembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 499, 266, 63));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 246, 235));
        jLabel4.setText("RISKY RESTO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 33, 159, 38));

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 246, 235));
        jLabel5.setText("Risky Wahyu");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 978, 105, 24));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 246, 235));
        jLabel6.setText("Owner");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 1000, 43, 20));

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnOut.png"))); // NOI18N
        btnKeluar.setBorder(null);
        btnKeluar.setBorderPainted(false);
        btnKeluar.setContentAreaFilled(false);
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnOut-hover.png"))); // NOI18N
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 983, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-mainMenu.png"))); // NOI18N
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kolomPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomPencarianActionPerformed

    public JTable getTblKaryawan() {
        return tabelDaftarKaryawan;
    }

    public JTextField getTxtSearch() {
        return kolomPencarian;
    }

    public JButton getBtnSidebarBeranda() {
        return btnSideBeranda;
    }
    
    public JButton getBtnSidebarPesanan() {
        return btnSidePesanan;
    }

    public JButton getBtnSidebarDaftarMenu() {
        return btnSideDaftarMenu;
    }
    
    public JButton getBtnSidebarMeja() {
        return btnSideMeja;
    }
    
    public JButton getBtnSidebarPembayaran() {
        return btnSidePembayaran;
    }

    public JButton getBtnCari() {
        return btnCari;
    }

    public JButton getBtnTambahMenu() {
        return btnTambahMenu;
    }
    
    private void kolomPencarianFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kolomPencarianFocusGained
        if (kolomPencarian.getText().equals(CARI_PLACEHOLDER)) {
            kolomPencarian.setText(""); // Hapus placeholder
            kolomPencarian.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_kolomPencarianFocusGained

    private void kolomPencarianFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kolomPencarianFocusLost
        if (kolomPencarian.getText().trim().isEmpty()) {
            kolomPencarian.setText(CARI_PLACEHOLDER); // Tampilkan placeholder
            kolomPencarian.setForeground(PLACEHOLDER_COLOR);
        }
    }//GEN-LAST:event_kolomPencarianFocusLost

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new karyawan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSideBeranda;
    private javax.swing.JButton btnSideDaftarMenu;
    private javax.swing.JButton btnSideKaryawan;
    private javax.swing.JButton btnSideMeja;
    private javax.swing.JButton btnSidePembayaran;
    private javax.swing.JButton btnSidePesanan;
    private javax.swing.JButton btnTambahMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kolomPencarian;
    private javax.swing.JTable tabelDaftarKaryawan;
    // End of variables declaration//GEN-END:variables
}
