/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_oop.view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Lorem Ipsum25
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_form = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        label_info = new javax.swing.JLabel();
        password_form = new javax.swing.JPasswordField();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_form.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        username_form.setBorder(null);
        getContentPane().add(username_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 360, 40));

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_login.png"))); // NOI18N
        btn_login.setText("Login");
        btn_login.setBorder(null);
        btn_login.setBorderPainted(false);
        btn_login.setContentAreaFilled(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_login.setMaximumSize(new java.awt.Dimension(0, 0));
        btn_login.setMinimumSize(new java.awt.Dimension(0, 0));
        btn_login.setPreferredSize(new java.awt.Dimension(0, 0));
        btn_login.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/use_hover_btn_login.png"))); // NOI18N
        btn_login.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 580, 150, 70));

        label_info.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(label_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 370, 20));

        password_form.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password_form.setBorder(null);
        password_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_formActionPerformed(evt);
            }
        });
        getContentPane().add(password_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 360, 40));

        back.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/use_bak.png"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-430, -60, 1710, 926));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_formActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginActionPerformed

    public JButton login_btn() {
        return btn_login;
    }

    public JTextField get_username() {
        return username_form;
    }

    public JPasswordField get_password() {
        return password_form;
    }

    public JLabel label_info() {
        return label_info;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel label_info;
    private javax.swing.JPasswordField password_form;
    private javax.swing.JTextField username_form;
    // End of variables declaration//GEN-END:variables
}
