/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_oop.view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Lorem Ipsum25
 */
public class login extends javax.swing.JFrame {
    
    private final String USER_PLACEHOLDER = "Masukkan Email atau Username Anda";
    private final String PASS_PLACEHOLDER = "Masukkan Password Anda";
    private final java.awt.Color PLACEHOLDER_COLOR = new java.awt.Color(153, 153, 153);

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        getContentPane().requestFocusInWindow();
        this.setLocationRelativeTo(this);
        setInitialPlaceholder();
    }
    
    private void setInitialPlaceholder() {
        // Untuk Username
        username_form.setText(USER_PLACEHOLDER);
        username_form.setForeground(PLACEHOLDER_COLOR);
        
        // Untuk Password
        password_form.setEchoChar((char) 0);
        password_form.setText(PASS_PLACEHOLDER);
        password_form.setForeground(PLACEHOLDER_COLOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_info = new javax.swing.JLabel();
        username_form = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        password_form = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1660, 562));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_info.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        label_info.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(label_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 631, 370, 20));

        username_form.setBackground(new java.awt.Color(252, 250, 248));
        username_form.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        username_form.setBorder(null);
        username_form.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_formFocusLost(evt);
            }
        });
        username_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_formActionPerformed(evt);
            }
        });
        getContentPane().add(username_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 468, 420, 27));

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn- masuk.png"))); // NOI18N
        btn_login.setBorder(null);
        btn_login.setBorderPainted(false);
        btn_login.setContentAreaFilled(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_login.setMaximumSize(new java.awt.Dimension(0, 0));
        btn_login.setMinimumSize(new java.awt.Dimension(0, 0));
        btn_login.setPreferredSize(new java.awt.Dimension(0, 0));
        btn_login.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btn-masuk-hover.png"))); // NOI18N
        btn_login.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 700, 510, 63));

        password_form.setBackground(new java.awt.Color(252, 250, 248));
        password_form.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        password_form.setBorder(null);
        password_form.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_formFocusLost(evt);
            }
        });
        password_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_formActionPerformed(evt);
            }
        });
        getContentPane().add(password_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 587, 420, 27));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RISKY RESTO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 236, 254, 60));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(125, 125, 125));
        jLabel4.setText("Email or Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 416, 172, 27));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(125, 125, 125));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 535, 88, 27));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selamat datang kembali! Harap login ke akun Anda.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 299, 470, 27));

        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ingat-saya.png"))); // NOI18N
        jCheckBox1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ingat-saya-Hover.png"))); // NOI18N
        jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ingat-saya-Selected.png"))); // NOI18N
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 654, 100, 21));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lupa-password.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lupa-password-hover.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 653, 123, 23));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/form-login.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 368, 619, 442));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_formActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginActionPerformed

    private void username_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_formActionPerformed
    
    private void username_formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_formFocusGained
        if (username_form.getText().equals(USER_PLACEHOLDER)) {
        username_form.setText(""); // Hapus placeholder
        username_form.setForeground(java.awt.Color.BLACK); // Ubah warna ke hitam
        }
    }//GEN-LAST:event_username_formFocusGained

    private void username_formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_formFocusLost
        if (username_form.getText().trim().isEmpty()) {
        username_form.setText(USER_PLACEHOLDER); // Set placeholder kembali
        username_form.setForeground(PLACEHOLDER_COLOR); // Ubah warna ke abu-abu
        }
    }//GEN-LAST:event_username_formFocusLost

    private void password_formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_formFocusGained
        String passwordText = new String(password_form.getPassword());

        if (passwordText.equals(PASS_PLACEHOLDER)) {
        password_form.setText(""); // Hapus placeholder
        password_form.setForeground(java.awt.Color.BLACK); // Ubah warna ke hitam
        password_form.setEchoChar('•'); // Aktifkan karakter gema (bintang/titik)
        }
    }//GEN-LAST:event_password_formFocusGained

    private void password_formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_formFocusLost
        String passwordText = new String(password_form.getPassword());

        if (passwordText.trim().isEmpty()) {
        password_form.setEchoChar((char) 0); // Nonaktifkan karakter gema (tampilkan teks normal)
        password_form.setText(PASS_PLACEHOLDER); // Set placeholder kembali
        password_form.setForeground(PLACEHOLDER_COLOR); // Ubah warna ke abu-abu
        }
    }//GEN-LAST:event_password_formFocusLost

    public JButton login_btn() {
        return btn_login;
    }

    public JTextField get_username() {
        return username_form;
    }

    public JPasswordField get_password() {
        return password_form;
    }

    public JLabel label_info() {
        return label_info;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label_info;
    private javax.swing.JPasswordField password_form;
    private javax.swing.JTextField username_form;
    // End of variables declaration//GEN-END:variables
}
